export const init = {
    data: {
        firstName: '',
        surName: '',
        lastName: '',
        date: new Date(),
        email: '',
        phone: '',
        distance: '',
        payment: '',
        grantCreateProfile: false,
        login: '',
        password: '',
    },
    messages: {
        firstName: '',
        surName: '',
        lastName: '',
        date: '',
        email: '',
        phone: '',
        distance: '',
        payment: '',
        login: '',
        password: '',
        auth: '',
        offer: '',
        registration: '',
        update: '',
    },
    logged: false,
};
